### PR TITLE
Update fp

### PR DESCRIPTION
**Pull request by Restorn**
I've made initial redesign of fingerprint UI to match Material Design. Also I've removed delay after incorrect scan, so now you can retry much faster, without waiting. Later I'll make it look more AOSP-like.

Screenshots: https://imgur.com/a/xnhjj
APK: https://mega.nz/#!2JAWgYCL!VEdh_h4TylH2EkBBRjl2MyEJ0SodUyhP2T1IIB-_Lxs

### CODE REVIEW

**Comment by valascus** [comment]
Can it now be used for more then 5 fingers?

**Comment by walter79** [comment]
10 finger are enabled.

https://github.com/visi0nary/android_device_elephone_p8000/commit/3f932200925fd0a98dd316a9f5458d5dd416244b

**Comment by walter79** [comment]
Will test you new fingerprint app.

**Comment by valascus** [comment]
Not those 10. You can only record up to 5 fingers in the app we're using.
I will test it too.

**Comment by valascus** [comment]
No, i can't set more then 5 fingers. 
Can u change it to like 10?
Also, is it possible to implement it on the system ui?

**Comment by walter79** [comment]
Fingerprint/fp/src/com/silead/fp/utils/FpControllerNative.java
-   public static final int IDENTIFY_MAX = 5;
  -  public static final int IDENTIFY_MAX = 10;

**Comment by janengelmohr** [comment]
Great work! I will check it out later today :)

**Comment by janengelmohr** [comment]
Thank you very much!

**Comment by anibalribeiro** [comment]
@visi0nary can you modify this line:
public static final int IDENTIFY_MAX = 5;
To 10?
Enabling 10 times, you satisfy users like me who wants to add more than 5 fingers and remains the same for the users who just want 5.

**Comment by Restorn** [comment]
@anibalcezarr this line changes only numer of tries when unlocking the device, not an actuall numer of fingerprints you can add.

**Comment by anibalribeiro** [comment]
@Restorn @visi0nary It is possible to increase the number of fingerprints ?

**Comment by valascus** [comment]
Finally someone that gets what i meant to! thanks @Restorn !! 
U got it now, @walter79 ? xD

**Comment by Restorn** [comment]
@anibalcezarr So far I wasn't able to do that, I'm afraid that this might be hardcoded into libs which we don't have sources to. But it still requires further investigation.

**Comment by janengelmohr** [comment]
I think the same @Restorn. I will increase IDENTIFY_MAX to 10 and set some flag so you actually have to unlock manually once that limit is reached. At the moment it is enough to turn the screen off and on again which renders this measurement useless.

**Comment by anibalribeiro** [comment]
How easy it is to compile the apk and test? I'm programmer but never have written one single line for mobile xD
I've read the code from this folder: https://github.com/visi0nary/android_device_elephone_p8000/tree/cm-12.1/MediaTek/Fingerprint/fp
And I guess that is really possible to add more fingerprints.

**Comment by janengelmohr** [comment]
Since this is a normal app it should be possible to compile it standalone and then just swap the .apk on the device.

**Comment by janengelmohr** [comment]
BTW how do you like this change? https://github.com/visi0nary/android_device_elephone_p8000/commit/72dc31bacebe389d7a42c58a1e71cf58c89e0952

I personally prefer it because of haptic feedback for both cases (success and failure)

**Comment by Restorn** [comment]
@visi0nary I think three quick vibrations are a little overshoot, two would be enough.

**Comment by janengelmohr** [comment]
@Restorn yea I was thinking the same actually. My point for three is that it is more distinguishable to one but it is probably too much, yep. Will test out two ;)

**Pull request merged**
